[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.3"
tokio = { version = "1", features = ["full"] }
opus = "0.3.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_millis = "0.1.1"
futures-util = "0.3.24"
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
native-tls = "0.2.10"
url = "2.3.1"
